USE [NORTHWND]
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('Employees') AND NAME ='PostalCode') 
BEGIN
	  PRINT 'Index exists'
END
Else
Begin
CREATE NONCLUSTERED INDEX [PostalCode] ON [dbo].[Employees]
(
	[PostalCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
End
GO